export const SET_PATIENT_URN = 'SET_PATIENT_URN'
export const SET_PATIENT_NAME = 'SET_PATIENT_NAME'
export const SET_EVENT = 'SET_EVENT'
export const ADD_EVENT = 'ADD_EVENT'
export const SET_MEDICINE = 'SET_EVENT'
export const ADD_MEDICINE = 'ADD_MEDICINE'
